### ISSUE TITLE
Automate installation - Docker

### ISSUE THREAD

**Issue by tyteck** [ForestAdmin/lumber#214]
Hi there 
A few monthes ago I've try to run forestAdmin on my server. I failed mainly due to the fact I was not familiar with node/npm ecosystem.
I want to give it a try again, but this time I would want to run it within a docker container through a mysql datasource and totally automated. 
I have 2 problems with that.
I've found some docker-compose for postgres (https://github.com/ForestAdmin/forest-live-demo-lumber/blob/master/docker-compose.yml) and mongodb (https://github.com/ForestAdmin/forest-live-demo-express-mongoose/blob/master/docker-compose.yml) datasource but none for mysql.
Inspired by those I've set my environnements variable to 
MYSQL_HOST=<MYSQL_SERVER_HOST>
MYSQL_DB=<MYSQL_DATABASE_NAME>
MYSQL_USER=<MYSQL_DATABASE_USER>
MYSQL_PASSWORD=<MYSQL_DATABASE_PASSWORD>
Is it correct ?

Now the forest (lumber) installation require a "lumber login" and "lumber generate" which are asking some more details.
RUN     lumber login
? What's your email address?  Removing intermediate container be1886ebd4a8

RUN     lumber generate
? What's the database type?  (Use arrow keys)
❯ postgres 
  mysql 

in order to fully automate this installation is it possible to set env variables (not that secure but only to give it try) or a secret ?
Thanks by advance

**Comment by tyteck** [comment]
I've create a repo (if you want to have a look)
https://github.com/tyteck/forestAdmin-docker

**Comment by tyteck** [comment]
By the way I've made small advances on that.
.env file is more like this
DATABASE_URL=mysql://<USER>:<PASSWORD>@<HOST>:<PORT><DATABASE_NAME>
FOREST_AUTH_SECRET=<FOREST_AUTH_SECRET>
FOREST_ENV_SECRET=<FOREST_ENV_SECRET>

But when I run docker with thoses elements, my container doesn't care. 
I still need to `lumber login`, `lumber generate`, `cd my_forest_project`, `npm install` and finally `npm start`.
Is there a way ?

**Comment by SeyZ** [comment]
Hi @tyteck thanks for this suggestion!

It's actually already possible on the `devel` branch. We've worked on the dockerization of the generated application:

![image](https://user-images.githubusercontent.com/519129/55781276-15e85a80-5aaa-11e9-9151-0db31441d8a4.png)

Can you confirm this is what you'd like?

**Comment by SeyZ** [comment]
@tyteck I just released the 1.14.3 version that supports Docker. Let me know if it fit your requirements and I'll reopen this issue otherwise

**Comment by tyteck** [comment]
Not quite :)

```
Step 8/8 : RUN     lumber login
 ---> Running in 693caa7125d7
> Missing your email address in the command.
> Type lumber help for more information.
```
I would like to have a way to specify credentials to be used with `lumber login`. For example, if env variables like FOREST_EMAIL and FOREST_PASSWORD (or FOREST_ENCRYPTED_CRED) are set, lumber login don't ask for any credential and is using these.
On the same "model" I would like that `lumber generate` use ENV DATABASE_URL if set.

PS : I know that env variables are not secure within dockers, it is only for a "quick" test. If I could use FOREST_AUTH_SECRET and FOREST_ENV_SECRET it would be nice too :)

**Comment by tyteck** [comment]
I advanced one step at a time. This moment I have 2 pain points :
## Authentication with lumber login or generating .lumberrc
If I copy the .lumberrc in the container in the homedir of the user running container I am logged in. 
`lumber user`
You're logged as 
Great but I need to authenticate once to create the .lumberrc. Is there a way to call api with email, forest_auth_secret and forest_auth_token to get a auth token (that I could thrown in ~/.lumberrc) ?

## DATABASE_SCHEMA env variable
When running `lumber generate fooproject`, 
if DATABASE_SCHEMA is empty/not set 
  installation is asking me What's the database schema? [optional]
if DATABASE_SCHEMA=""
  SequelizeDatabaseError: Table 'myDb."".fooTable' doesn't exist
if DATABASE_SCHEMA=null
  SequelizeDatabaseError: Table 'myDb.null.fooTable' doesn't exist

If I manually run `lumber generate` and type enter, everything is fine, project is generated.
I cannot set a linux env variable to nothing so is it possible, in prompter.js, to ask for it only if FOREST_DB_DIALECT !='mysql' (I don't know for mongo, postgres or mssql but mysql don't care about schema :))

I updated my docker automation to reflect what I've done til now. Thanks for your help.

**Comment by tyteck** [comment]
Hi guys
I'm still working on automating a proper forest installation with docker. And still failing.
I have 2 containers.
- one mysql server 
- the forest admin one

From the forestAdmin one, using mysql-cli, I can connect to the mysqlServer container 

`root@2a321a3795c9:/var/opt/forestAdmin# mysql -uOBFUSCATED_USER -pOBFUSCATED_PASSWORD -hmysqlServer -P3306 OBFUSCATED_DBNAME
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 314
Server version: 5.7.25 MySQL Community Server (GPL)

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [OBFUSCATED_DBNAME]>`

when I try to lumber generate it fails.
`lumber generate -c mysql://OBFUSCATED_USER:OBFUSCATED_PASSWORD@mysqlServer:3306/OBFUSCATED_DBNAME petitchameau
? What's the IP/hostname on which your admin panel API will be running?  forest.mydomain.com
? What's the port on which your admin panel API will be running?  3000
> Cannot connect to the database due to the following error:
> SequelizeHostNotFoundError: getaddrinfo ENOTFOUND mysqlserver mysqlserver:3306`

Have you an idea ?

**Comment by marcperrinp** [comment]
Hi @tyteck, 

we are currently working on a new installation process where using Docker is an option. It still needs work but you can already test it by following [our documentation](https://docs.forestadmin.com/documentation/getting-started/installation/install-in-lumber#install-using-docker).

About your lumber generate issue (with mysql), this should be fixed if you update to lumber to the latest version (2.1.2).
